# This is a basic workflow to help you get started with Actions

name: Autograding

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  pull_request:
    branches: [ "feedback", "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Get Student Repo
      - name: Student Repo
        uses: actions/checkout@v3
        with:
          path: student_code

      # Get Grading Repo
      - name: Master Repo
        uses: actions/checkout@v3
        with:
          token: ${{secrets.F22_3155_PAT}}
          repository: csci3155/pppl-labdev
          path: master_code

      # Prep grading repo
      - name: Prep Grading
        run: ./gradepreplab1.sh .
        working-directory: ./master_code

      # Grade the current
      - name: Grade current 
        run: ./gradelab1.sh ../student_code . ../ 2>&1 | tee ../grading.log
        working-directory: ./master_code
        timeout-minutes: 10

      # Display the score
      - name: Display Score
        run: tail -n 1 grading.log

      - name: Upload Grading Log
        uses: actions/upload-artifact@v3
        with:
          name: grading.log
          path: grading.log
